### ISSUE TITLE
Simplify usage of image.ymls vs parse-pkgs generation

### ISSUE THREAD

**Issue by deitch** [zededa/zenbuild#87]
Continuing conversation from [here](https://github.com/zededa/zenbuild/pull/85#issuecomment-480645274):

@rvs said:

> what to do with image.ymls
> using a floating tag (like snapshot or latest) will be fine, but I don't remember linuxkit and Docker caching policies for these. Do you?

The question of "what do with image `ymls`" means, how do we simplify the usage of the ymls. Right now, the image ymls are templated. For example, `rootfs.yml` comes from [rootfs.yml.in](https://github.com/zededa/zenbuild/blob/master/images/rootfs.yml.in), which looks as follows (partial):

```yml
kernel:
  image: KERNEL_TAG
  cmdline: "rootdelay=3"
init:
  - GRUB_TAG
  - DTREES_TAG
  - FW_TAG
  - XEN_TAG
  - GPTTOOLS_TAG
  - DOM0ZTOOLS_TAG
  - linuxkit/init:v0.5
  - linuxkit/runc:v0.5
  - linuxkit/containerd:v0.5
  - linuxkit/getty:v0.5
```

The `*_TAG` are replaced via [parse-pkgs.sh](https://github.com/zededa/zenbuild/blob/master/parse-pkgs.sh) to actual specific packages, e.g. `zededa/kernel:abcdef55667aa`.

This creates some challenges, as documented in [BUIILD.md](https://github.com/zededa/zenbuild/blob/master/docs/BUILD.md#parse-pkgs).

Notably, it leaves the actual build source `yml` outside of version control.

The purpose of this issue is to discuss what the **flow** should be, in terms of both people and automated systems, when building EVE images. The technology implementation should follow that desired flow.
